services:
  node:
    build: .
    volumes:
      - ./app:/home/node/app/app
    working_dir: /home/node/app
    command: "npm run start"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  couchdb:
    image: couchdb:latest
    container_name: couchdb-log
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
volumes:
  couchdb_data: